server:
  port: 7867
spring:
  application:
    name: optimisticlocking
  jackson:
    default-property-inclusion: non_null
  datasource:
    dynamic:
      primary: master
      strict: false
      datasource:
        master:
          url: jdbc:mysql://127.0.0.1:3306/spring_cloud_alibaba_practice_master?characterEncoding=utf8&connectTimeout=1000&socketTimeout=3000&autoReconnect=true&useUnicode=true&useSSL=false&serverTimezone=UTC
          username: root
          password:
          maximumPoolSize: 10
          minimumIdle: 2
          ideleTimeout: 600000
          connectionTimeout: 30000
          maxLifetime: 1800000
        slave_1:
          url: jdbc:mysql://127.0.0.1:3306/spring_cloud_alibaba_practice_slave1?characterEncoding=utf8&connectTimeout=1000&socketTimeout=3000&autoReconnect=true&useUnicode=true&useSSL=false&serverTimezone=UTC
          username: root
          password:
          maximumPoolSize: 10
          minimumIdle: 2
          ideleTimeout: 600000
          connectionTimeout: 30000
          maxLifetime: 1800000
        slave_2:
          url: jdbc:mysql://127.0.0.1:3306/spring_cloud_alibaba_practice_slave2?characterEncoding=utf8&connectTimeout=1000&socketTimeout=3000&autoReconnect=true&useUnicode=true&useSSL=false&serverTimezone=UTC
          username: root
          password:
          maximumPoolSize: 10
          minimumIdle: 2
          ideleTimeout: 600000
          connectionTimeout: 30000
          maxLifetime: 1800000
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl